create table public.document_chunk (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  id_document uuid not null,
  chunk_index smallint generated by default as identity not null,
  content text not null,
  id_company uuid not null,
  embedding extensions.halfvec not null,
  constraint document_chunk_pkey primary key (id),
  constraint document_chunk_id_company_fkey foreign KEY (id_company) references company (id) on update CASCADE on delete CASCADE,
  constraint document_chunk_id_document_fkey foreign KEY (id_document) references document (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;