-- 1= 'pending' → 2='processing' → 3='ready' →

create table public.file_status (
  id smallint generated by default as identity not null,
  status text not null,
  constraint file_status_pkey primary key (id)
) TABLESPACE pg_default;