create table public.log (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  id_staff uuid not null,
  note text not null,
  id_company uuid not null,
  constraint log_pkey primary key (id),
  constraint log_id_company_fkey foreign KEY (id_company) references company (id) on update CASCADE on delete CASCADE,
  constraint log_id_staff_fkey foreign KEY (id_staff) references staff (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;