create table public.log (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  note text not null,
  id_company uuid not null,
  email_staff text not null,
  constraint log_pkey primary key (id),
  constraint log_id_company_fkey foreign KEY (id_company) references company (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;